### PR TITLE
Tests for existence_check in tools.py

### PR DESCRIPTION
**Pull request by joshmgrant**
I've written a (basic!) test class for the `tools.existence_check()` function. As this function is pretty widely used all over proselint, I thought having a test harness for it would help any future refactoring or bug fixing.

### CODE REVIEW

**Comment by suchow** [comment]
Nice, thanks for this. Can you squash these commits together? Otherwise, it looks ready to merge.

**Comment by joshmgrant** [comment]
@suchow Ok, I can squash them together once the current CI checks have completed

**Comment by suchow** [comment]
@joshmgrant Our test coverage is only 15% — lot's of room for improvement. I saw your blog and that you're knowledgeable about testing software. I'd be interested to hear your thoughts and suggestions about improving our testing of proselint.

**Comment by joshmgrant** [comment]
@suchnow Thanks for reading my stuff! I'd love to give some suggestions for testing. I'll have a think and we can discuss further :)

**Pull request merged**
