### PR TITLE
Custom checks through command line

### LINKED ISSUE #702: custom `.proselintrc` path
Is there a way to point a custom path for the `.proselintrc` ? e.g. `$(pwd)`.

If not - I can try to implement it.

### PR DESCRIPTION
**Pull request by ankita240796**
closes #702 

- Added mechanism to specify a custom checks folder.

### CODE REVIEW

**Comment by rriemann** [comment]
Would it be possible to configure the checks folder also in the `.proselintrc`?

**Comment by rriemann** [comment]
I have installed proselint as root. However, when I run this command, it fails because of missing rights or because the folder "." exists already.

It must be clear that this command changes the system configuration permanently.

**Comment by ankita240796** [comment]
@rriemann I have added the feature to configure custom checks to ``.proselintrc``.

**Comment by rriemann** [comment]
So if I have a checks folder configured in my `~/.proselintrc`, on every call of proselint, all (new) files will be copied to the checks directory?

Is there a check in the code if the destination directiory in writeable?

**Comment by ankita240796** [comment]
When a command line option check is used with the specified path, the specified directory get copied to ``checks`` folder and the checks are marked as true in ``.proselintrc``.

**Comment by suchow** [comment]
Hi @ankita240796, thank you for the PR!  :)

Would it be possible to:

1. Split this PR into two smaller PRs, one that adds the custom path feature and another that adds the custom checks feature? I'm ready to accept the former immediately, but need to think more deeply about the latter.

2. Add documentation to the "Checks section" of the README and to [the docs](https://github.com/amperser/proselint/blob/master/site/_posts/2014-06-10-utility.md) showing how to use the custom path feature?

**Comment by ankita240796** [comment]
Sure @suchow I will make the changes as suggested by you!

**Comment by jima80525** [comment]
Will this change cover the case where the user wants a custom .proselintrc file in the current directory?  

I'm willing to add that feature if not, as I'd like to use this tool in an automated toolchain (on circleci) but I'd rather have the rc file be part of my repo, not requiring it to be in the ~ directory.

**Comment by ankita240796** [comment]
Hi @suchow, sorry for delay on this. I was busy with my academics. I have made the changes as suggested by you. Please take a look, Thanks!

**Comment by ankita240796** [comment]
Hi @jima80525, this change intended to add a feature for providing a custom location for ``.proselintrc`` but as suggested by @suchow, I have reverted that feature from this PR. I can submit another PR for that if you are not working on that feature, Thanks!

**Comment by ankita240796** [comment]
Hi @suchow any updates on this?

**Comment by ankita240796** [comment]
I have also issued a separate PR for adding custom path: #865

**Comment by Nytelife26** [comment]
Custom checks are something I was thinking about earlier, so this is a nice surprise. I'll triage now and I'm fairly sure we implemented a config path already but I'll triage the other too/

**Comment by ankita240796** [comment]
> Custom checks are something I was thinking about earlier, so this is a nice surprise. I'll triage now and I'm fairly sure we implemented a config path already but I'll triage the other too.

Ok Thanks @Nytelife26, let me know if I can help with something :)

**Comment by Nytelife26** [comment]
I'm not entirely sure copying the new checks into the checks folder is the best way to go about this. One would assume supplying a custom checks folder via CLI, rather than via configuration, persists solely for that command.

**Comment by ankita240796** [comment]
> I'm not entirely sure copying the new checks into the checks folder is the best way to go about this. One would assume supplying a custom checks folder via CLI, rather than via configuration, persists solely for that command.

Should I take that up and add a fix in this PR?

**Comment by Nytelife26** [comment]
> Should I take that up and add a fix in this PR?

If you so wish! Any help is greatly appreciated.
If you need anything or have any questions, do let me know. Glad to have
you here.

**Comment by ankita240796** [comment]
Sure, I am working this, will update once I finalize the design approach.

**Pull request closed without merging**
