### PR TITLE
fix(checks): ignore case in misc.but for lowercase "but"

### LINKED ISSUE #98: Add rule about starting paragraph with "But"
```
Justin Jungé to me
Show more
Mar 23
Hi Jordan,

I'm grading more tutorial essays and keep making a similar set of comments about a problem that proselint might be able to flag.  

Here's one instance of the comment:

Don't start a paragraph with "but."

Every paragraph should be self-contained.  "But" implies referring back to the previous paragraph to know what contrast is being made. 

On a similar note, the first sentence of a new paragraph should use nouns instead of pronouns.  Pronouns often require referring back to previous sentences, breaking self-containment.

In this particular case, "but" can simply be deleted, because the sentence is sufficiently informative (effectively self-contained).  I'm merely flagging this use to explain why style guides forbid using "but" at the start of a paragraph.


Flagging paragraphs that start with "but" should be trivial to implement.  Recognizing paragraph first-sentences with only pronouns and no nouns also seems feasible, though it won't catch every version of the general infraction.  
…
```

### LINKED ISSUE #745: misc.but reports false positive
Run proselint on the following file:

```
This line is OK,
but this is not.
```

The following error is reported:

```
misc.but No paragraph should start with a 'But'.
```

That "but" is not only not at the beginning of the paragraph, it's not even at the beginning of a sentence.

### PR DESCRIPTION
**Pull request by blueyed**
Resolves #98. Resolves #745.

### CODE REVIEW

**Comment by KVGarg** [comment]
Fixes Issue #98 , #605

**Comment by KVGarg** [comment]
Hey @blueyed , i was going through your changes and found an issue,
```
Hey i am testing

on but keyword,
but, wait, line four is wrong.
but, wait, why this line is not giving any warning?
```
last line should give a warning/error that the paragraph should not start with `but`.  I know that `but` should be in Caps as it's a new line but that is not a problem as i have added a check for that to raise warning whether sentence begins with Caps letter or not. Can you just modify the `regex` to solve this issue?

**Comment by KVGarg** [comment]
Fixes Issue #98 , #605, #745

**Comment by blueyed** [comment]
@KVGarg 
Thanks for triaging.
I assume the previous comment (I've received via email) is not valid anymore?

**Comment by KVGarg** [comment]
Which comment ? because when I referenced other issues there were no other comments.

**Comment by blueyed** [comment]
Deleted it already, but it was about multiple "but"s and the last one not being caught, asking to change the regexp.  Might have been lost during the GitHub outage yesterday then maybe (i.e. emailed, but not posted here)?!

**Comment by KVGarg** [comment]
Ok @blueyed

**Review by Nytelife26 — APPROVED** [review]

**Review by suchow — APPROVED** [review]

**Pull request merged**
