### PR TITLE
Emacs Flycheck plugin packaging

### LINKED ISSUE #527: How to install proselint plugin on Emacs
I have installed `proselint` and it works on the terminal. But when I try to include `proselint` plugin code on my `init.el` Emacs does not initialise. Is it possible to give some guidance about the installation process?

### PR DESCRIPTION
**Pull request by mavit**
This scaffolding turns `flycheck-proselint.el` into an Emacs package, which will enable it to be included in package repositories such as [MELPA](https://melpa.org/) for easy installation.

This fixes #527.

Once this is done, I will submit the following recipe to MELPA to get the package included in their repository:
```elisp
(flycheck-proselint
 :fetcher github
 :repo "amperser/proselint"
 :files ("plugins/flycheck/flycheck-proselint.el"
         "README.md"
         "LICENSE.md"))
```

### CODE REVIEW

**Comment by suchow** [comment]
@mavit Thanks. Do you know of any way to test or demonstrate that this works as intended? Maybe something that can be added to our test suite? I don't use Emacs or Flycheck and thus don't have any way of testing this out.

**Comment by mavit** [comment]
I see that Flycheck itself runs tests in Travis using a testing framework called buttercup, so it's certainly possible.  We can't copy and paste Flycheck's harness, however, since it's GNU GPL licensed.

I'll have a look into it when I find time.  Would you be satisfied with testing against a single version of Emacs, rather than the Cartesian product of Emacs and Python versions?

**Comment by m-cat** [comment]
Any update on this? Would be very convenient if this were available as a package through melpa.

**Comment by mavit** [comment]
Is there reluctance to merge this, or have you simply not had time to look at it?  Would it be better for me to split the Flycheck plugin out into it's own repository, I wonder?

**Comment by suchow** [comment]
Done, thanks for the contribution! And quite sorry for the delay.

**Comment by robstewart57** [comment]
Is there a reason why flycheck-proselint isn't listed as a melpa package?

https://melpa.org/#/?q=proselint

**Comment by mavit** [comment]
Support for `proselint` is now built in to Flycheck, so no plugin is required.  https://github.com/flycheck/flycheck/pull/1304

**Comment by robstewart57** [comment]
Excellent! So when I enable flycheck-mode, proselint is enabled by default if my computer has a proselint executable in `$PATH`? Or do I manually have to enable proselint checks when running flycheck against a particular buffer?

**Comment by mavit** [comment]
You need to tell Flycheck to which modes is should apply `proselint`, if that mode is not [included by default](https://github.com/flycheck/flycheck/blob/master/flycheck.el#L8674).  For example:
```lisp
(flycheck-add-mode 'proselint 'org-mode)
```

But this is not a support forum, so such questions are better directed to http://www.flycheck.org/en/latest/community/get-help.html

**Pull request merged**
