### PR TITLE
Add possibility to use proselint as pre-commit hook

### PR DESCRIPTION
**Pull request by aairey**
Created a pre-commit hook as per https://pre-commit.com/#new-hooks

### CODE REVIEW

**Comment by suchow** [comment]
@aairey Thank you. Can you rebase this over master and include it in the plugins list in the README?

**Comment by aairey** [comment]
@suchow done and pushed.

**Comment by suchow** [comment]
Thank you!

**Comment by aairey** [comment]
Quick guide how to use it in your own git repository:
Add the following to your `.pre-commit-config.yaml in the root of your git repo:
```- repo: https://github.com/amperser/proselint.git
  sha: 0.10.0
  hooks:
    - id: proselint```
run the following to install the hook:
`pre-commit install-hooks`
to test on all files run:
`pre-commit run -a proselint`
to add this to your git pre-commit hooks
`pre-commit install`

**Pull request merged**
