### PR TITLE
Fix issue #272

### PR DESCRIPTION
**Pull request by j10sanders**
Fixed issue #272

### CODE REVIEW

**Comment by j10sanders** [comment]
Can anyone help me figure out why Travis CI is giving me this error?  I don't understand what it is checking:

`The command "pep257 . --match='.*\.py'" exited with 1.
$ bundle exec danger`

**Comment by j10sanders** [comment]
Hi @michaelpacer and @suchow!  I am hoping to get some feedback on my pull requests.  I'd like to make sure that I should continue working on this project - I'm quite enthusiastic about it.

I'm wondering:
1. Is the Travis CI error meaningful?  
2. If the error is meaningful, will my pull requests get accepted/considered if I resubmit, and the test passes?

Thanks!
-Jon

**Comment by suchow** [comment]
@j10sanders Thanks for all these PRs, much appreciated. Here's the pep257 error that's blocking this:

```
pep257 . --match='.*\.py'
./proselint/checks/misc/institution_name.py:1 at module level:
        D400: First line should end with a period (not 's')
```

I'm going to add you as a collaborator now so that you can open branches directly off amperser/proselint/master.

**Comment by j10sanders** [comment]
thank you!  I'll resubmit these pull requests to pass the checks.

**Comment by michaelpacer** [comment]
LGTM, merged.

(Note to others, in the GitHub view it looks like the alignment in the `proselint.rc` is off. In actuality, it's not, must be a weird display bug on GitHub's part.)

**Pull request merged**
