### PR TITLE
test: bypass cache in pytest runs

### PR DESCRIPTION
**Pull request by joshmgrant**
Starting a PR to address #1151

### CODE REVIEW

**Comment by Nytelife26** [comment]
Thank you for the pull request! This is, at present, a much-needed fix.

However, Pytest's cache is not the cause of the issue, unfortunately. All Pytest does is cache test file IDs to make collection faster. The real issue lies within the caching used by our lint functions with the memoize decorator - this is not cleared between tests currently, which causes runs to be oblivious to source code changes.

**Comment by joshmgrant** [comment]
Thanks for the feedback! I feel like I remember this issue (or something like that) from a long time ago. I'll see if I can rework some of the `test\` code to help with this issue.

**Comment by Nytelife26** [comment]
@joshmgrant That doesn't remove the shelving, it just takes out the part where it gets closed afterwards.

**Comment by Nytelife26** [comment]
I'll push what I've been working on. At present, I'm making a function called
in the setup for each test that **should** clear the cache for the check.
Emphasis on should. At the minute, something seems to be going wrong with
tests, though, so that needs to be fixed.

If you'd like, you can take a look or pick up where I left off. For now, I'm
signing off for the day, so I'll continue tomorrow.

**Comment by joshmgrant** [comment]
Yeah, I was hoping I could use a quick hack to get around the caching issue. It looks like my idea didn't work :)

I guess the main question I have is: should we find a way to test the individual checks without memoization? Or should we find a better way to structure the pytest tests to allow for caching somehow?

**Comment by Nytelife26** [comment]
> I guess the main question I have is: should we find a way to test the
> individual checks without memoization? Or should we find a better way to
> structure the pytest tests to allow for caching somehow?

It would be ideal to bypass the cache lookup or clear the cache prior to
the tests. The former would be better, but I believe it would also be
significantly more complicated to implement - unless we use an
environment variable that gets set in the setup of the test suite, and
then in the memoization function if the variable is present it will not
index the cache.

**Comment by joshmgrant** [comment]
So I was able to find a way to get undecorated functions imported into a module. This means we can test the "unmemoized" methods directly from each check module/class in the tests. The only catch is - wait for it - this currently only works for Python 3. I can see if I can update the logic for Python 2 and Python 3 if needed. Let me know if this is what you're looking for!

**Comment by Nytelife26** [comment]
That's certainly something. Honestly I didn't know you could do that, so it's certainly a learning experience. Fortunately, that's not a catch - we recently decided to drop support for Python 2 anyway.

[Nytelife26 - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=132n80)	[132n80]

On June 22, 2021 at 3:38 GMT, joshin4colours ***@***.***> wrote:

So I was able to find a way to get undecorated functions imported into a module. This means we can test the "unmemoized" methods directly from each check module/class in the tests. The only catch is - wait for it - this currently only works for Python 3. I can see if I can update the logic for Python 2 and Python 3 if needed. Let me know if this is what you're looking for!

**Comment by Nytelife26** [comment]
@joshmgrant I altered your latest commit. Rather than changing the `this_check.check` to `this_check(...)` and then altering it to return the wrapped version in every file, we can simply use `this_check.check.__wrapped__` since there will never be a not-memoized check and there will never be a test run that doesn't want the original check.

**Comment by Nytelife26** [comment]
I can confirm, these changes have fixed the problem. Brilliant work, @joshmgrant.

I'll experiment with some better ways of doing this as I mentioned in my previous comment, and then we can get this reviewed and merged.

**Comment by Nytelife26** [comment]
@suchow This is ready for review if you wouldn't mind :)

**Review by Nytelife26 — APPROVED** [review]

**Pull request merged**
