### PR TITLE
Implement After the Deadline redundancy

### PR DESCRIPTION
**Pull request by alecglassford**
Implement redundancy rule as described in issue 279 https://github.com/amperser/proselint/issues/279

I browsed the list and manually took out a few rules that didn't make much sense to me, namely:

```
["It is",             ["It is what it is"]],
["at a later at a",   ["at a later date at a"]],
["linger",            ["linger on"]],
["lose",              ["lose out on"]],
```

This is also a really large list of rules, many of which I think are maybe sort of sketch/I suspect will lead to false positives. E.g. `["shut",              ["shut down"]],` and `["range",             ["dynamic range"]],`

I don't know if someone wants to comb through here/test more thoroughly, e.g. on the ["clean" corpora](https://github.com/amperser/proselint/tree/master/corpora).

### CODE REVIEW

**Comment by suchow** [comment]
Thanks, Alec, much appreciated. It's going to be some time before we can merge this, because (as you mentioned) individual entries require some careful consideration before adopting, and because we may reorganize things a bit so that we can logically groups related checks (compare `wallace.redundancy`, `garner.redundancy`, and `nordquist.redundancy`).

As a first pass, I'm going to make a bunch of line-by-line comments now.

**Comment by suchow** [comment]
@alecglassford Holy moly, I made it to the end. That was enlightening — I now know why these other tools have so many false alarms.

Interested in fixing this up?

**Comment by alecglassford** [comment]
@suchow Yup, I'll go through the rest of your comments and try to have a cleaned up version this weekend.

**Comment by suchow** [comment]
@alecglassford Any luck on this?

**Comment by suchow** [comment]
Closed by #500, thanks for contributing!

**Pull request closed without merging**
