### PR TITLE
Update README.md with instructions on running tests

### PR DESCRIPTION
**Pull request by vikasgorur**
Is proselint in Python2 or 3? py.test seems to run fine for me with Python 3.5. Please let me know which is the correct version of Python developers are supposed to use and I'll update the README.

Thanks for this wonderful tool and I'm excited to contribute more!

### CODE REVIEW

**Comment by michaelpacer** [comment]
Proselint should be both Python 2 and Python 3 compatible. 

My suggestion is aim at working in Python 3, and then work to bring back Python 2 compatibility. 

A good way to be able to try with both is to use a virtual environment manager toolset like `conda` or `virtualenv` + `virtualenvwrapper`.

**Comment by vikasgorur** [comment]
Got it, thanks.

**Comment by michaelpacer** [comment]
It's a good point though that explaining all of that just to run tests is a bit excessive for that part of the README. Can you think of any way to make sure tests are run for both without needing to first teach people how to use virtual environments?

**Comment by vikasgorur** [comment]
I agree that it's too much to explain virutalenv. I just wrote your comment about doing development in Python 3 for now.

I think it's safe to assume that anyone who's willing to fix compatibility issues between Python 2 & 3 already knows how to use virtualenv.

**Comment by vikasgorur** [comment]
Now that I've seen what's involved in getting tests to run with both Python 2 & 3, I think this PR is inadequate. I'll discard this and come up with something better.

**Pull request closed without merging**
