### PR TITLE
Add phrasal adj for issues #543 and #537

### PR DESCRIPTION
**Pull request by kylesezhi**
Add:
- Real estate tycoon
- English-language learners

to phrasal adjectives.

This is my first pull request to proselint. I love what you're doing and please let me know if I've done anything wrong.

### CODE REVIEW

**Comment by suchow** [comment]
Thanks! I'm working on getting Danger back up and running so that this will pass on Travis.

**Comment by suchow** [comment]
Okay, it's ready to merge. Thanks for your contribution!

Can I interest you in another?

**Comment by kylesezhi** [comment]
Absolutely! 😄

**Comment by suchow** [comment]
@kylesezhi I looked through the list of open issues and found a couple that could make good second commits — maybe #564 or #275. Are there any areas of software development or writing you're particularly interested in?

**Comment by kylesezhi** [comment]
OK! I will look into those. I had also looked at the technical English one (left a comment there), but if these are a better fit, they sound good!

**Pull request merged**
