### PR TITLE
Fix misattributed Twain quote

### PR DESCRIPTION
**Pull request by hugovk**
>  There is no substantive evidence that Mark Twain said this.

... 

> In conclusion, the earliest evidence in 1935 points to William Allen White as the creator of this comical advice. The evidence is not direct, and the teller of the anecdote stated that it happened “several years ago”, so its veracity is not clear. Yet, QI thinks William Allen White is the best candidate for ascription.

http://quoteinvestigator.com/2012/08/29/substitute-damn/

### CODE REVIEW

**Comment by suchow** [comment]
Thanks for the research and correction. I'm ready to merge this, except I'm having trouble confirming that William Allen White's last name is Allen White? If not, I'd prefer to name the module `white`. Do you have a source on this?

**Comment by suchow** [comment]
Encyclopædia Britannica refers to him as "White" (http://www.britannica.com/biography/William-Allen-White), so let's go with that.

**Comment by michaelpacer** [comment]
Lgtm

**Comment by hugovk** [comment]
Fixed!

**Comment by suchow** [comment]
Perfect, thank you.

**Pull request merged**
