### PR TITLE
chore: repo housekeeping

### LINKED ISSUE #1148: ci: migrate pyup -> dependabot
Dependabot is now a GitHub native feature that supports poetry and will not open hundreds of individual pull requests (since it can aggregate changes). I believe it would be beneficial to cease usage of the third party tool and switch to Dependabot, but I am open to thoughts on this.

CC: @suchow

### PR DESCRIPTION
**Pull request by Nytelife26**
## This relates to...

With our recent updates and preparation to re-enter active maintenance, it would be prevalent to do some housekeeping.

## Changes

- Fixes #1148 by adding dependabot
- Adds issue & PR templates
- Refactors labelling

### CODE REVIEW

**Comment by Nytelife26** [comment]
@suchow just a ping in case you haven't seen this yet

**Comment by suchow** [comment]
Can you rebase over master and make sure it passes CI, then we’ll merge?

**Comment by Nytelife26** [comment]
@suchow Tests now pass.

**Comment by suchow** [comment]
Yay!

**Pull request merged**
