### PR TITLE
Add recommendations from Edward P. Bailey

### PR DESCRIPTION
**Pull request by david-a-wheeler**
Add recommendations from the book "Plain English at Work"
  by Edward P. Bailey, Jr., Oxford University Press, 1996.

### CODE REVIEW

**Comment by suchow** [comment]
Hi David, thanks for the contribution. I think it's unlikely we'll be able to merge this in its current form — I don't want us to get in the habit of banning words. On the other hand, I do see value in using plain language when possible. Maybe there's a way to have this check trigger only if it finds many examples of the non-preferred forms in a single document? Do you know of any good examples that we could use to test it?

**Comment by david-a-wheeler** [comment]
I imagine some sort of frequency should be easy to determine. Is there already routine to do that?

Also

**Comment by david-a-wheeler** [comment]
I suggest modifying the contribution information to state that you don't want to get in the habit of banning words. Obviously you do it, with words like very.

**Comment by david-a-wheeler** [comment]
Well, the "Wondermark" awards are rewards for especially writing: http://centerforplainlanguage.org/wondermark/

One "winner" is here:
https://www.uscis.gov/humanitarian/consideration-deferred-action-childhood-arrivals-process/frequently-asked-questions

I could resubmit with some sort of "% words triggering", using this as an example of something that should trigger it.

**Comment by david-a-wheeler** [comment]
I intend to create a new version, based on these comments, so closing this pull request.

**Pull request closed without merging**
